api/urls.py
from django.urls import path, re_path
from .views import *
from django.urls import include, path
from rest_framework import routers
from . import views

from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from .views import NotaViewSet

# Cruds Rapidos gestionados por Django Rest Framework
router = DefaultRouter()
router.register(r'notas', NotaViewSet, basename='nota')

urlpatterns = [
    path('', index, name='index'),
    
    # Inicio de sesión y registro Firebase
    path("logout/", logout_view, name="logout"),

    # PERFIL
    path('obtener-perfil/', obtener_perfil, name='obtener-perfil'), # Del navbar y para el useContext: usePerfil
    path('perfil/<uuid:pk>/', PerfilDetailView.as_view(), name='perfil-detail'),
    path('perfil/<uuid:pk>/info/', InfoPerfilView.as_view(), name="perfil-info"),
    
    
    # CAMPAÑAS
    # El primer enlace es de prueba general de campañas
    path('campanas/', CampanaListView.as_view(), name='campana-list'),
    path('mis-campanas/<uuid:pk>/', MisCampanasView.as_view(), name="mis-campanas"),
    path('mis-campanas/crear/', CrearCampanaView.as_view(), name='crear-campana'),
    
    
    # * Enlaces dentro de campañas
    # GENERAL
    path('campanas/<int:pk>/', CampanaDetailView.as_view(), name='campana-detail'), 
    path('campanas/<int:pk>/party/', PartyListView.as_view(), name='party-list'), 
    path('campanas/<int:pk>/party/<uuid:jug>/delete/', PartyMemberDeleteView.as_view(), name='party-member-delete'), 
    
    # SESIONES
    path('campanas/<int:campana_id>/sesiones/', SesionesPorCampanaView.as_view(), name='sesiones-por-campana'),
    path('campanas/<int:campana_id>/sesiones/<int:pk>/', SesionDetailView.as_view(), name='sesion-detail'),
    path('campanas/<int:campana_id>/sesiones/crear/', SesionCreateView.as_view(), name='sesion-create'),

    path('campanas/<int:campana_id>/sesiones/<int:pk>/comenzar/', SesionComenzar.as_view(), name='sesion-comenzar'),
    path('campanas/<int:campana_id>/sesiones/<int:pk>/programar/', SesionProgramar.as_view(), name='sesion-programar'),
    path('campanas/<int:campana_id>/sesiones/<int:pk>/finalizar/', SesionFinalizar.as_view(), name='sesion-finalizar'),
    
    # INVITACIONES
    path("campanas/<int:campana_id>/invitacion/", CrearInvitacionView.as_view(), name="crear-invitacion"),
    path("unirse/<uuid:codigo>/", UnirseCampanaView.as_view(), name="unirse-campana"),

    # NOTAS (WEBSOCKETS)
    path('', include(router.urls)),
    
    # ENCUENTROS
    path('campanas/<int:campana_id>/encuentros/', EncuentroListView.as_view(), name='encuentros-por-campana'),
    path('campanas/<int:campana_id>/encuentros/crear/', CrearEncuentroView.as_view(), name='crear-encuentro'),
    path("campanas/<int:campana_id>/encuentros/<int:encuentro_id>/participantes/crear/", CrearParticipanteEncuentroView.as_view(), name="crear-participante"),
    path("campanas/<int:campana_id>/encuentros/<int:pk>/", EncuentroDetailView.as_view(), name="encuentro-detail"),
    path("campanas/<int:campana_id>/encuentros/<int:pk>/comenzar/", EncuentroComenzar.as_view(), name="encuentro-comenzar"),
    path("campanas/<int:campana_id>/encuentros/<int:pk>/programar/", EncuentroProgramar.as_view(), name="encuentro-programar"),
    path("campanas/<int:campana_id>/encuentros/<int:pk>/finalizar/", EncuentroFinalizar.as_view(), name="encuentro-finalizar"),
    path("campanas/<int:campana_id>/encuentros/<int:pk>/turno/<int:turno>/", EncuentroCambiarTurno.as_view(), name="encuentro-finalizar"),
    path('campanas/<int:campana_id>/encuentros/activos/', EncuentrosActivosView.as_view(), name='encuentros-activos'),
    path('campanas/<int:campana_id>/encuentros/<int:pk>/participantes/<int:participante_pk>/', EncuentroParticipanteActualizar.as_view(), name="participante-actualizar"),
    
    # MISIONES
    path('campanas/<int:campana_id>/misiones/', MisionListView.as_view(), name='misiones-por-campana'),
    
    # * Fin enlaces dentro de campañas
    
    # PERSONAJES
    path('mis-personajes/<uuid:pk>/', MisPersonajesView.as_view(), name='mis-personajes'),
    #path('mis-personajes/', PersonajeViewSet.as_view(), name='personaje-viewset'),
    path('personajes/<int:pk>/', PersonajeDetailView.as_view(), name='personaje-detail'),

    path("personajes/<int:personaje_id>/inventario/", InventarioPorTipoView.as_view(), name="inventario-por-tipo"),
    path('mis-personajes/crear/', CrearPersonajeView.as_view(), name='crear-personaje'),

    # ENEMIGOS
    path('enemigos/', EnemigoListView.as_view(), name="enemigo-list"),
    path('enemigos/<int:pk>/', EnemigoDetailView.as_view(), name="enemigo-detail"),
    path('enemigos/crear/', CrearEnemigoView.as_view(), name="enemigos-list"),
    
    # OTROS
    path('idiomas/', IdiomaList.as_view(), name="idioma-list"),
]

dicenotes/urls.py
from django.contrib import admin
from django.urls import path, include
from api.views import index, NotaViewSet
from rest_framework.routers import DefaultRouter

from django.conf import settings
from django.conf.urls.static import static

router = DefaultRouter()
router.register(r'notas', NotaViewSet, basename='nota')

urlpatterns = [
    path('', index,name='index'),
    path('admin/', admin.site.urls),
    path('dndapp/', include('dndapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
    #API
    path('api/', include('api.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dndapp/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path("", views.index, name="index"),
    
    # Campaña
    path("campanas/", views.CampanaListView.as_view(), name="campana-list"),
    path("campanas/new/", views.formularioCampana, name="formularioCampana"),
    path("campanas/<uuid:pk>/", views.CampanaDetailView.as_view(), name="campana-detail"),
    path("campanas/edit/<uuid:pk>/", views.CampanaUpdate.as_view(), name="modificarCampana"),
    path("campanas/delete/<uuid:pk>/", views.CampanaDelete.as_view(), name="eliminarCampana"),
    
    # Encuentro
    path("campanas/<uuid:pk>/encuentros/new/", views.formularioEncuentro,  name="formularioEncuentro"),
    
    # Perfil
    path("perfiles/<int:pk>/", views.perfilDetalle, name="perfil-detail"),
    path("perfiles/<int:pk>/edit/", views.PerfilUpdate.as_view(), name="modificarPerfil"),
    path("perfiles/<int:pk>/personajes/", views.PersonajeListView.as_view(), name="personaje-list"),
    path("perfiles/<int:pk1>/personajes/<int:pk2>", views.PersonajeDetailView.as_view(), name="personaje-detail"),
    
    # Personaje
    path("perfiles/<int:pk>/personajes/new/", views.formularioPersonaje, name="formularioPersonaje"),
]

dndapp/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser, Permission
from colorfield.fields import ColorField
import uuid
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete
from django.utils.timezone import now
from django.contrib.auth import get_user_model
from django.conf import settings

# * Gracias a la libreria random, podemos tirar dados *#

import random

# * Se merece su propio espacio *#

#from firebase_auth.models import CustomUser

#* MODELOS DE DICE & NOTES

CustomUser = get_user_model()

class Perfil(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True
    )
    apodo = models.CharField(max_length=100)
    biografia = models.TextField(max_length=500, blank=True, null=True)
    avatar = models.ImageField(
        upload_to="avatares/",
        null=True,
        blank=True,
        default="avatares/default_avatar.jpg",
    )

    def __str__(self):
        return self.apodo


# Señal para crear automáticamente un perfil cuando se crea un usuario
# @receiver(post_save, sender=CustomUser)
# def crear_perfil_automatico(sender, instance, created, **kwargs):
#     if created:
#         # Obtener la parte del email antes del "@"
#         base_apodo = instance.email.split("@")[0] if instance.email else "usuario"
#         apodo = base_apodo
#         counter = 1

#         # Buscar un apodo único
#         while Perfil.objects.filter(apodo=apodo).exists():
#             apodo = f"{base_apodo}{counter}"
#             counter += 1

#         Perfil.objects.create(user=instance, apodo=apodo)

#? No usado en v1.0
# Imagen: puede usarse tanto en el interior de las sesiones de una campaña como en un apartado propio de las campañas. Pensado para poner imagenes de NPCs y mapas a modo de informacion. No usado en v1.0.
class ImagenCampana(models.Model):
    nombre = models.CharField(max_length=50)
    imagen = models.ImageField(upload_to="img_campanas/")
    descripcion = models.CharField(max_length=100, blank=True, null=True)
    fecha_subida = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo


# Campaña
class Campana(models.Model):
    nombre = models.CharField(max_length=50)
    dungeon_master = models.ForeignKey(
        Perfil,
        on_delete=models.CASCADE,
        related_name="campanas_creadas",
        null=True,
        blank=True,
    )
    descripcion_corta = models.TextField(max_length=100, null=True, blank=True)
    imagen = models.ImageField(
        upload_to="campanas/",
        null=True,
        blank=True,
        default="campanas/default_campana.jpg",  # Imagen predeterminada
    )
    descripcion_larga = models.TextField(null=True, blank=True)
    imagenes = models.ManyToManyField(ImagenCampana, blank=True)

    def __str__(self):
        return self.nombre

    @staticmethod
    def crear_permisos():
        content_type = ContentType.objects.get_for_model(Campana)
        permisos = [
            ("gestionar_sesiones", "Puede gestionar sesiones"),
            ("gestionar_misiones", "Puede gestionar misiones"),
            ("gestionar_encuentros", "Puede gestionar encuentros"),
            ("gestionar_personajes", "Puede gestionar personajes"),
            ("crear_invitaciones", "Puede crear invitaciones")
            ]

#? No usado en v1.0
# Asignación de roles a nivel de aplicación, aplicables a cada jugador de cada campaña
class RolCampana(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    permisos = models.ManyToManyField(Permission, blank=True)
    
    def __str__(self):
        return self.nombre

# Modelo de control de roles y perfiles con personajes por campañas
class ParticipanteCampana(models.Model):
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    campana = models.ForeignKey(Campana, on_delete=models.CASCADE)
    rol = models.ForeignKey(RolCampana, on_delete=models.SET_NULL, null=True)
    personaje = models.ForeignKey('Personaje', on_delete=models.CASCADE, null=True, blank=True)
    
    class Meta:
        unique_together = ("perfil", "campana") # Un usuario solo tiene 1 rol por campaña
        
    def __str__(self):
        return f"{self.perfil} en {self.campana} como {self.rol}"

class Invitacion(models.Model):
    campana = models.ForeignKey(Campana, on_delete=models.CASCADE, related_name="invitaciones")
    codigo = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    creador = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    creado_en = models.DateTimeField(default=now)
    expiracion = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"Invitación a {self.campana.nombre} - Código: {self.codigo}"

# Una sesión es una parte de la campaña. Aquí se podrán añadir notas y reproducir encuentros.
class Sesion(models.Model):
    campana = models.ForeignKey(
        Campana, on_delete=models.CASCADE, related_name="sesiones"
    )
    nombre = models.CharField(max_length=100)
    fecha_inicio = models.DateTimeField(blank=True, null=True)
    ubicacion = models.CharField(max_length=250, blank=True, null=True)
    imagenes = models.ManyToManyField(ImagenCampana, blank=True)
    ESTADO_SESION = [
        ("programada", "Programada"),
        ("en_curso", "En curso"),
        ("finalizada", "Finalizada"),
    ]
    estado = models.CharField(
        max_length=50, choices=ESTADO_SESION, default="programada"
    )

    def __str__(self):
        return f"Sesión '{self.nombre}', de '{self.campana.nombre}"


# Una nota puede estar en sesiones, personajes, items, hechizos, etc.
# Se relaciona con el modelo de contenido genérico de Django
class Nota(models.Model):
    creador = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    contenido = models.TextField(max_length=10000, null=True, blank=True)

    TIPO_NOTA = (
        ("privada", "Privada"),
        ("publica", "Pública"),
        ("dm", "DM y Jugador"),
    )
    tipo = models.CharField(max_length=10, choices=TIPO_NOTA)

    # Relación genérica para asociar la nota a cualquier modelo
    content_type = models.ForeignKey(
        ContentType, on_delete=models.CASCADE, null=True, blank=True
    )
    object_id = models.PositiveIntegerField(
        null=True, blank=True
    )  # Era UUID, no podia reconocer los demas modelos
    content_object = GenericForeignKey("content_type", "object_id")

    def __str__(self):
        return f"Nota de {self.creador.apodo} en {self.content_object} ({self.get_tipo_display()})"


#? No usado en v1.0
# Etiquetas para clasificar items y hechizos
class Tag(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    color_fondo = ColorField(default="#f25f29")
    color_texto = ColorField(default="#FFFFFF")

    def __str__(self):
        return f"{self.nombre} - Fondo: {self.color_fondo}, Texto: {self.color_texto}"


#? No usado en v1.0.
class Item(models.Model):
    nombre = models.CharField(max_length=100)
    peso = models.FloatField(null=True, blank=True)  # Peso en libras
    valor = models.PositiveIntegerField(null=True, blank=True)  # Monedas de oro
    efecto = models.CharField(
        max_length=100, blank=True, null=True
    )  # Efecto del ítem si tiene
    informacion = models.TextField(
        max_length=2000, blank=True, null=True
    )  # Descripción adicional
    tags = models.ManyToManyField("Tag", blank=True)  # Relación con etiquetas
    imagen = models.ImageField(upload_to="items/", null=True, blank=True)
    
    def tipo_real(self):
        if hasattr(self, 'arma'):
            return 'Arma'
        elif hasattr(self, 'equipamiento'):
            return 'Equipamiento'
        elif hasattr(self, 'consumible'):
            return 'Consumible'
        elif hasattr(self, 'tesoro'):
            return 'Tesoro'
        return 'Item'

    def __str__(self):
        return f"{self.nombre} ({self.tipo_real()})"

#? No usado en v1.0.
class Arma(models.Model):
    item = models.OneToOneField(Item, on_delete=models.CASCADE, related_name='arma')
    puntaje_fijo = models.IntegerField(blank=True, null=True)  # Daño fijo (Ej: 5)
    puntaje_dados = models.CharField(
        max_length=10, blank=True, null=True
    )  # Daño con dados (Ej: 2d6)
    alcance = models.CharField(
        max_length=50, blank=True, null=True
    )  # Ej: "Cuerpo a cuerpo"


    def __str__(self):
        if self.puntaje_fijo is not None:
            return f"{self.item.nombre} (Arma - {self.puntaje_fijo} daño fijo)"
        elif self.puntaje_dados:
            return f"{self.item.nombre} (Arma - {self.puntaje_dados} daño)"
        return f"{self.item.nombre} (Arma)"


#? No usado en v1.0.
class Equipamiento(models.Model):
    EQUIPAMIENTO_TIPOS = [
        ("ropa", "Ropa"),
        ("accesorio", "Accesorio"),
        ("ligera", "Armadura ligera"),
        ("media", "Armadura media"),
        ("pesada", "Armadura pesada"),
        ("otro", "Otro"),
    ]
    item = models.OneToOneField(Item, on_delete=models.CASCADE, related_name='equipamiento')
    tipo = models.CharField(max_length=50, choices=EQUIPAMIENTO_TIPOS)
    puntaje_fijo = models.IntegerField(blank=True, null=True)  # +HP fija (Ej: 5)

    def __str__(self):
        return f"{self.item.nombre} ({self.tipo})"


#? No usado en v1.0.
class Consumible(models.Model):
    item = models.OneToOneField(Item, on_delete=models.CASCADE, related_name='consumible')
    duracion = models.CharField(max_length=50, blank=True, null=True)  # Ej: "1 hora, 2 minutosm 3 turnos"
    usos = models.PositiveIntegerField(
        default=1, blank=True, null=True
    )  # Cuántas veces se puede usar

    def __str__(self):

dndapp/forms.py
from django import forms
from django.forms import ModelForm
from .models import Encuentro, Campana, Personaje
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

# Parte de la aplicación de prueba con Django Templates
class CampanaForm(forms.ModelForm):
    class Meta:
        model = Campana
        fields = "__all__"
        
class EncuentroForm(forms.ModelForm):
    class Meta:
        model = Encuentro
        fields = "__all__"
                
class PersonajeForm(forms.ModelForm):
    class Meta:
        model = Personaje
        fields = "__all__"

dndapp/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
    <title>Dice & notes</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="icon" href="{% static 'images/d20-logo.png' %}" type="image/png"/>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
          <ul class="sidebar-nav">
            
            <a href="{% url 'index' %}">
              <img
              src="{% static 'images/d20-logo.png' %}"
              alt="Dice & Notes"
              style="width: 70px; height: 70px"
              />
            </a>
            <br>
            <p>Dice & Notes</p>
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'campana-list' %}">Campañas</a></li>

          </ul>
          
          

          <ul class="sidebar-nav">
            … {% if user.is_authenticated %}
            <li>User: {{ user.get_username }}</li>
            
            <li><a href="{% url "perfil-detail" user.perfil.pk %}">Mi perfil</a>
            
            <li>
              <form id="logout-form" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-link">Logout</button>
              </form>
            </li>

        
            {% else %}
            <li>
              <a href="{% url 'login' %}?next={{ request.path }}">Login</a>
            </li>
            {% endif %} …
            
          </ul>

          {% endblock %}
        </div>
        <div class="col-sm-10">{% block content %}{% endblock %}</div>
      </div>
    </div>
  </body>
</html>

dndapp/templates/campana-detail.html
{% extends "base_generic.html" %}
{% block content %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<div>
<h1>{{campana.titulo}}</h1>
<p>{{campana.info}}</p>
<p>Creada por: <a href="{% url "perfil-detail" campana.dungeon_master.pk %}">{{campana.dungeon_master}}</a></p>
    
    {% if campana.dungeon_master == user.perfil %}
    <a href="{% url "modificarCampana" campana.pk %}"><button>Modificar</button></a>
    <a href="{% url "eliminarCampana" campana.pk %}"><button>Eliminar</button></a>
    <br/>
    {% endif %}
<hr/>

<h3>Información de la campaña</h3>
<p>{{campana.descripcion_larga}}</p>


</div>






{% endblock %}

dndapp/templates/campana-list.html
{% extends "base_generic.html" %}
{% block content %}
<h1>Campañas</h1>


{% if user.is_authenticated %}
<a href="{% url "formularioCampana" %}"><button>Crear Campaña</button></a>
{% endif %}
<hr/>

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

<div class="card-set">
{% for campana in campana_list %}
<div class="card">
<h3>{{campana.titulo}}</h3>
<p>{{campana.info}}</p>
<p>Creada por <a href="{% url "perfil-detail" campana.dungeon_master.pk %}"</a>{{campana.dungeon_master.nombre_visible}}</p>


<div>
<a href="{% url "campana-detail" campana.pk %}" class="enter"><button>Entrar</button></a>
</div>
</div>
{% endfor %}
</div>



{% endblock %}

dndapp/templates/index.html
{% extends "base_generic.html" %}
{% block content %}
<h1>Dice & Notes</h1>
<p>Bienvenido a la aplicación de gestión de partidas de rol.</p>
<p>Para empezar, puedes:</p>
<ul>
    <li><a href="{% url 'campana-list' %}">Ver las campañas disponibles</a></li>
</ul>
<p>Si eres el Dungeon Master de una campaña, puedes:</p>
<ul>
    <li><a href="{% url 'formularioCampana' %}">Crear una nueva campaña</a></li>
</ul>
<p>Si eres un jugador, puedes:</p>
<ul>
    {% comment "" %}
    <li><a href="{% url 'formularioPersonaje' request.user.perfil.pk %}">Crear un nuevo personaje</a></li>
    {% endcomment %}
</ul>

{% endblock %}

dndapp/templates/perfil-detail.html
{% extends "base_generic.html" %}
{%block content%}

{% load static %}
<img class="avatar" src="
{% if perfil.avatar%}
    {{perfil.avatar.url}}
    {% else %}
    {% static 'images/default_avatar.jpg' %}
{% endif %}
"/>
<h1>Perfil: {{perfil.nombre_visible}}</h1>
<p>{{perfil.biografia}}</p>

<a href="{% url "modificarPerfil" perfil.pk %}"><button>Editar</button></a>
<a href="{% url "formularioPersonaje" perfil.pk %}"><button>Crear personaje</button></a>

{%endblock%}

dndapp/templates/personaje-list.html
{% extends "base_generic.html"%}
{% block content %}
    <h1>Personaje List</h1>
    <ul>
        {% for personaje in personaje_list %}
            <li>{{ personaje.nombre }} - {{ personaje.raza }}</li>
        {% endfor %}
    </ul>
{% endblock %}